quad_x0: 0.0
quad_y0: 0.0
quad_z0: 0.0

arm_q1: -1.57
arm_q2: 1.57

goal_x: 3.0
goal_y: 3.0
goal_z: 3.0

obs_x: 1.0
obs_y: 1.0
obs_z: 1.0

obs_x2: 2.0
obs_y2: 2.0
obs_z2: 2.0

obs_r: 0.5

link1: 0.175
link2: 0.42

te: 5.0
numSteps: 15
